### ISSUE TITLE
Secrets do not reflect their new value after being updated in KeyVault

### ISSUE THREAD

**Issue by Lucasfernandez19** [btungut/azure-keyvault-secret-operator#3]
Secrets do not reflect their new value after being updated in KeyVault

**Comment by btungut** [comment]
@Lucasfernandez19 sorry for late reply. This will be the new future. Do you have any contribution ?

Best.

**Comment by btungut** [comment]
@Lucasfernandez19 sorry for late response. It is now supported with 1.0.7 version.
